module.exports = [
     {
        id: 1,
        name: 'Schoolkid',
        description: 'Catch Normal-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 2,
        name: 'Black Belt',
        description: 'Catch Fighting-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 3,
        name: 'Bird Keeper',
        description: 'Catch Flying-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 4,
        name: 'Punk Girl',
        description: 'Catch Poison-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 5,
        name: 'Ruin Maniac',
        description: 'Catch Rock-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 6,
        name: 'Hiker',
        description: 'Catch Ground-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 7,
        name: 'Bug Catcher',
        description: 'Catch Bug-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 8,
        name: 'Hex Maniac',
        description: 'Catch Ghost-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 9,
        name: 'Depot Agent',
        description: 'Catch Steel-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 10,
        name: 'Kindler',
        description: 'Catch Fire-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 11,
        name: 'Swimmer',
        description: 'Catch Water-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 12,
        name: 'Gardener',
        description: 'Catch Grass-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 13,
        name: 'Rocker',
        description: 'Catch Electric-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 14,
        name: 'Psychic',
        description: 'Catch Psychic-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 15,
        name: 'Slier',
        description: 'Catch Ice-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 16,
        name: 'Dragon Tamer',
        description: 'Catch Dragon-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 17,
        name: 'Fairy Tale Girl',
        description: 'Catch Fairy-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
    {
        id: 18,
        name: 'Delinquent',
        description: 'Catch Dark-type Pokemon.',
        bronze: 10,
        silver: 100,
        gold: 250,
        platinum: 1000,
    },
]